version: '3.8'

networks:
  backend:
    driver: bridge

services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    ports:
      - "8000:80"
    networks:
      - backend
    depends_on:
      - app

  app:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./:/var/www/html
    networks:
      - backend
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/volume/pgsql:/var/lib/postgresql/data
      - ./test.dump:/docker-entrypoint-initdb.d/test.dump
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/conf:/usr/local/etc/redis
